### PR TITLE
Update jquery.inputmask.bundle.js

### PR DESCRIPTION
**Pull request by bilalyilmax**
$("input").inputmask({alias:'numeric', groupSeparator: '.', radixPoint: ",", autoGroup: true, digits: 2, digitsOptional: false, suffix: ' TL', placeholder: '0.00', autoUnmask : true });

OLD UNMASK: 9.876.543,21 TL -> 9876543,21
NEW UNMASK: 9.876.543,21 TL -> 9876543.21

### CODE REVIEW

**Comment by RobinHerbots** [comment]
@bilalyilmax , 

Can you make the changes in the js folder instead of the bundle file.
Can you also provide some more info.

Thx

**Comment by bilalyilmax** [comment]
okey, i new. and my english not good.
but in turkish, decimal separator is comma.. so if unmask the input, comma is already there.. so we must change comma to dot.

9.876.543,21 TL -> 9876543,21 - this is wrong for js calculate..
9.876.543,21 TL -> 9876543.21 - must be this..

31f01e8 is true update..

**Comment by RobinHerbots** [comment]
@bilalyilmax , 

No problem, and as long we can understand each othe, ... ;-)

About the problem.

I know that you need the dot for parsing the value in javascript and do calculations, but when submitting the unmaskedvalue to a server (example ASP.NET/MVC) it will expect the decimal separator as defined in the user culture.  In your case a komma.  Modifying the default binder in asp.net is possible but not likely todo,  just submitting decimal values.  So I keep the decimal separator to the setting as defined in the mask.  

When you want todo some calculations on the javascript side, you have to convert the decimal separator to dot, or use some lib like jquery.globalize or alter the numeric alias as you did. 

Maybe I can add an option to indicate that unmaskedvalue should be a number?

**Comment by bilalyilmax** [comment]
Thansk for this information.. 
i looked jquery.globalize and i think this is big for just it.. But generally its good.
I use PHP-Symfony. i resource how to use in symfony.

**Pull request closed without merging**
