### PR TITLE
fix: fix server side undefined navigator

### PR DESCRIPTION
**Pull request by eduardoborges**
This PR try to solve problems with server side rendering.

Example of Next.Js err

image

### CODE REVIEW

**Comment by RobinHerbots** [comment]
@eduardoborges ,

This issue is already fixed by #2704

**Comment by maykon-oliveira** [comment]
I'm getting this error yet

> ReferenceError: navigator is not defined

**Comment by eduardoborges** [comment]
> I'm getting this error yet
> 
> 
> 
> > ReferenceError: navigator is not defined

Wasn't released yet :) 
on 5.1.0 roadmap

**Comment by oteka21** [comment]
same here!  😢

**Comment by gabrielsch** [comment]
isn't this related with `use client` in next.js 13? I think this lib should be only usable under client components since it needs access to browser APIs

**Pull request closed without merging**
