### PR TITLE
fix ssr issues when navigator is not defined

### LINKED ISSUE #6033: Use Inputmask plugin
### What version of Remix are you using?

1.15.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

- Installing Inputmask plugin https://github.com/RobinHerbots/Inputmask
- Try importing the library.

### Expected Behavior

Be able to use this browser library for masking inputs

### Actual Behavior

Output error:
> ReferenceError: navigator is not defined

It's weird because they are already validating if they can use the DOM: https://github.com/RobinHerbots/Inputmask/blob/5.x/lib/canUseDOM.js
Like this other RemixJS example: https://remix.run/docs/en/1.15.0/guides/constraints#uselayouteffect

### PR DESCRIPTION
**Pull request by jdnichollsc**
Closes https://github.com/remix-run/remix/issues/6033

### CODE REVIEW

**Comment by jdnichollsc** [comment]
@RobinHerbots hey mate, thanks for your help and please let me know what you think! <3

**Comment by RobinHerbots** [comment]
@jdnichollsc ,

Looks good!

**Comment by diegopamio** [comment]
Any clue when this will be released? Is there a workaround meanwhile?

**Comment by RobinHerbots** [comment]
@diegopamio ,
You can use the 5.0.9 beta version

**Comment by diegopamio** [comment]
thanks!

**Pull request merged**
