### PR TITLE
Add package.json

### PR DESCRIPTION
**Pull request by erbridge**
Adds npm compatability.

### CODE REVIEW

**Comment by RobinHerbots** [comment]
@erbridge, Thx

**Comment by erbridge** [comment]
No problem. You might consider [publishing to npm](https://www.npmjs.org/doc/cli/npm-publish.html), too.

**Comment by RobinHerbots** [comment]
Can this be automated somehow?  Every time I tag a new release?

**Comment by erbridge** [comment]
You could take a look at something like https://github.com/geddski/grunt-release or https://github.com/cmanzana/node-publish. You could probably combine that with Travis CI to make it happen automatically. I'm pretty new to npm, myself, so I can't be much more help than that.

In the meantime, having a `package.json` means someone can do `npm install RobinHerbots/jquery.inputmask#<tree-ish>`, it just won't be registered on npmjs.org.

Another link: http://liddellj.com/publishing-to-bower-npm-and-nuget-using-grunt/

**Pull request merged**
