### PR TITLE
"onfocuslost" event - fires when focus is lost, but mask isn't complete.

### PR DESCRIPTION
**Pull request by dasmfm**

### CODE REVIEW

**Comment by RobinHerbots** [comment]
In which case would you use this functionality?  You can always bind to the blur event.

Anyway I should merge the check with the clearincomplete, otherwise the checkval happens twice on blur.
Can you rename the event to onincomplete

**Comment by dasmfm** [comment]
I use it when I need to do something (for example, draw exclamation mark) when user leaves the field uncompleted.

For example: I need user to write ten digits. He wrote only 6 and click somewhere outside, so I need to tell him "hey, you didn't write full number".

In case of using "onblur" I'll need to check for mask completition by hands, but in my case your plugin do the stuff.

You're right, it's better to merge check with clearincomplete, should you do it? Or I can do it by myself.

I'll rename event right now.

**Comment by RobinHerbots** [comment]
Actually, a check like you mention should be done by validation and not
handled by the inputmask, ... anyway with this event you can implement
something like a progress indicator while typing the mask.

Can you make the changes.  I will pull in the changes.

best regards

Robin

2012/2/7 dasmfm <
reply@reply.github.com

**Comment by dasmfm** [comment]
Sorry, I'm new one on github, so it looks like I've made new pull request instead of changing this one :(

**Comment by RobinHerbots** [comment]
No problem ;-)

2012/2/7 dasmfm <
reply@reply.github.com

**Pull request closed without merging**
