### PR TITLE
Fix the check for leap years in 'dd-mm-yyyy' alias

### PR DESCRIPTION
**Pull request by ghost**
It seems this piece of code was copied from yyyy-dd-mm alias, but wasn't adjust to dd-mm-yyyy mask.

### CODE REVIEW

**Comment by ghost** [comment]
Hi! Haven't received any feedback. Any issues with the patch?

**Comment by RobinHerbots** [comment]
@anatoly-mytrucking , 

I just haven't got the time to have a look at it.  Sorry

**Comment by RobinHerbots** [comment]
@anatoly-mytrucking , 

Thx for the PR and bringing the issue to my attention.  But I moved the leapyear check to the postValidation callback.

**Comment by ghost** [comment]
All good. Thanks!

**Pull request closed without merging**
