### PR TITLE
Fix for #586 - Numeric Grouping Delete

### PR DESCRIPTION
**Pull request by ghost**
Fixes issue where grouping is not handled properly on delete/backspace.

### CODE REVIEW

**Comment by RobinHerbots** [comment]
@swd120 , 

Can you point out what you have changed as the pull request also shows some space char changes etc.

**Comment by RobinHerbots** [comment]
@swd120 , 

Ok, found the change!  Thx!

**Comment by ghost** [comment]
Yeah, sorry about that - Somehow the spacing got messed up when I changed it in the editor.  Glad you found it!

There's still an issue when using a prefix that I'm working on.

**Comment by RobinHerbots** [comment]
Open an issue for it with an example. Then I can have a look ;-)

2014-08-06 0:24 GMT+02:00 swd120 notifications@github.com:

**Pull request merged**
