### PR TITLE
Issue #1122: tests fixed - the issue needs to be reopened

### PR DESCRIPTION
**Pull request by htmlmasta**
The old test didn't work properly, so the issue needs to be reopened

### CODE REVIEW

**Comment by RobinHerbots** [comment]
@htmlmasta , 
Thx for the PR.  I added the new test instead of updating the old test.

The issue is also fixed ;-)

**Comment by htmlmasta** [comment]
Great! Tnx for fix. 

However, the old test doesn't work properly yet:
this test was created for the issue #1122 and after `$("#testmask").Type("$ 99,999,999.00");` the value of the input becomes `$ 90.99` instead of expected `$ 99,999,999.00`.

**Comment by RobinHerbots** [comment]
@htmlmasta , 

What is wrong with that test?  Does it fail?

**Comment by htmlmasta** [comment]
It checks `Inputmask("currency").isValid("$ 90.99");` instead of `Inputmask("currency").isValid("$ 99,999,999.00");`

**Pull request closed without merging**
