### PR TITLE
Fix mask position on android

### PR DESCRIPTION
**Pull request by whooehoo**

### CODE REVIEW

**Comment by RobinHerbots** [comment]
@whooehoo , 

Did you test this on android?   The position does not match the inputfield.

**Comment by whooehoo** [comment]
@RobinHerbots ,

Yes.

Last version bundle:
https://whooehoo.github.io/test/

With request:
https://whooehoo.github.io/test2/

Give me example code please, where position does not match the inputfield.

**Comment by RobinHerbots** [comment]
@whooehoo , 

I see it now.  It works!

Can you make the changes in the js/inputmask.js and leave the other property changes in (z-index)

**Comment by whooehoo** [comment]
@RobinHerbots ,

Sorry, but if i do this, mask will not work.

I delete this lines, because you createElement('span') and inline elements don't need height and width styles.

```
colorMask.width = (offset.width ? offset.width : offset.right - offset.left) + "px",
colorMask.height = (offset.height ? offset.height : offset.bottom - offset.top) + "px",
```

I delete z-index, because if input doesn't have attribute `style="z-index: "` getComputedStyle return 'auto' and this line sets `style="z-index: -1"` to span mask. After that mask will be under input.

```
colorMask.style.zIndex = isNaN(computedStyle.zIndex) ? -1 : computedStyle.zIndex - 1, 
```

Why are you set `z-index: -1`? Maybe i must change z-index line like that?

```
colorMask.style.zIndex = isNaN(computedStyle.zIndex) ? computedStyle.zIndex : computedStyle.zIndex - 1, 
```

**Comment by RobinHerbots** [comment]
@whooehoo , 

The element in focus is still the input, but the span shows the output.  The input type is password which disabled the predictive text; I made the input background and color transparent so it gets the feel of a normal masked input.  It is patchwork but it is the only way I see to fool the predictive text of the android keyboard.  The span needs to be behind the input So the z-index.

**Comment by RobinHerbots** [comment]
@whooehoo , 

I will merge the changes, and copy them over to the correct files.

**Comment by whooehoo** [comment]
@RobinHerbots ,

Thx.

Now span over input, i think you'll need add event 'click' on span, which 'focus' input. Only for Android.

**Comment by RobinHerbots** [comment]
@whooehoo , 

The fix does not work in all cases.  Have a look at https://jsfiddle.net/tzLa2oy9/41/

**Comment by whooehoo** [comment]
@RobinHerbots ,

Yes, my mistake.

Add new pull request with this fix:
https://github.com/RobinHerbots/Inputmask/pull/1405

I update your jsfiddle with request bundle:
https://jsfiddle.net/tzLa2oy9/49/

**Comment by PlayTimeAlex** [comment]
Hello guys. I am using last version and position is not totally fixed. You can check update of top example. 
https://jsfiddle.net/tzLa2oy9/50/

and you should set line height (line-height = height)

**Comment by RobinHerbots** [comment]
@PlayTimeAlex ,

Try with
https://jsfiddle.net/9zLgmLz6/

But the caret positioning needs some fix.

**Comment by RobinHerbots** [comment]
@PlayTimeAlex , 

Oh I see, can you create a seperate issue for it

**Pull request merged**
