### PR TITLE
Added event "preprocessafterpaste" in order to be able to do stuff right...

### PR DESCRIPTION
**Pull request by monoblaine**
Added event "preprocessafterpaste" in order to be able to do stuff right after a paste and right before the moment that raw text gets formatted by the plug-in.

### CODE REVIEW

**Comment by RobinHerbots** [comment]
@monoblaine, 

What do mean exactly with do stuff right.  Why do you need to preprocess?

**Comment by monoblaine** [comment]
I'm using the mask "(999) 999 9999" for phone inputs, but users generally want to paste the phone number from somewhere else right into the input box instead of typing it manually, and the phone number they copy generally includes number 0 at the beginning (0 212 555 55 55 for instance). Therefore I thought I could add such a preprocessor event in order to remove the extra "0" from the beginning, so that the pasted phone number gets inserted and formatted correctly.

I use the event handler in the following way and it works beautifully:

```
$phones.inputmask("(999) 999 9999", {
    preprocessAfterPaste : function (e) {
        var input = e.currentTarget,
            pastedRawValue = input._valueGet().replace(/(\W|_)*/g, "");

        if (pastedRawValue.charAt(0) === "0") {
            input._valueSet(pastedRawValue.substr(1));
        }
    }
});
```

**Comment by monoblaine** [comment]
Btw, I didn't mean to write "do stuff right", the title is cropped, sorry about that :)

**Comment by RobinHerbots** [comment]
@monoblaine, 

Indeed that can be usefull in that case.

But I would implement it as some kind of callback.  

Maybe call the option onBeforePaste and just call that in the paste event to preprocess the value.

**Comment by monoblaine** [comment]
Your solution is much more elegant, thank you!

**Comment by YAmikep** [comment]
Hi, 
I have kind of the same problem.
But it is not when the user copy paste the value => I store the phone numbers in the international format so when a page with numbers is loaded, the inputs contain the value as "+11234567890", and the mask is applied when the page is loaded so (112) 345-6789 is displayed instead of (123) 456-7890. 
Is there a way to access the initial value before the mask is applied to remove the +1 for example ?
Thanks

**Comment by RobinHerbots** [comment]
@YAmikep , 

I just added a new callback onBeforeMask which does exactly that  ;-)

**Pull request closed without merging**
