### PR TITLE
Add JSHint and JSCS

### PR DESCRIPTION
**Pull request by SimenB**
:warning: Not ready for merge

Are you interested in linting your sourcecode? I just threw this one quickly together, it's far from passing.

If you want to merge it, I'd be happy to go through and make the code pass. Just tell med what rules you want :smile:

### CODE REVIEW

**Comment by SimenB** [comment]
@RobinHerbots ping

**Comment by RobinHerbots** [comment]
I come back to this issue.  Some patience :-)  I am busy with my 7 days old
daughter.

Op 10:15 VR 24 Apr 2015 schreef Simen Bekkhus notifications@github.com:

**Comment by SimenB** [comment]
Oh :laughing: Congratulations! :fireworks:

**Comment by SimenB** [comment]
@RobinHerbots Hey, it seems like you're active again :smile: 

Are you interested in this? If you are, I'm happy to spend the time going through the codebase.

An option is to go for [standard](https://github.com/feross/standard). Less thinking, more doing :smile: Then you can [autoformat](https://github.com/maxogden/standard-format/) to fix most of the violations

**Comment by RobinHerbots** [comment]
@SimenB , 

Maybe I prefer to go for standard. , all those tools are great as long they do not ask extra effort, ...

**Comment by SimenB** [comment]
Sweet! Do you want me to do it, or do you want to do the first refactor yourself? Basically just running https://github.com/maxogden/standard-format/

I can fix remaining violations no prob afterwards

**Comment by RobinHerbots** [comment]
I will have a look at it, so that I am not totally chocked when I see modified code ;-)

**Comment by SimenB** [comment]
Haha, yeah. That's why I haven't done it, I don't want the git blame

On Wed, 22 Jul 2015 17:19 Robin Herbots notifications@github.com wrote:

> I will have a look at it, so that I am not totally chocked when I see
> modified code ;-)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RobinHerbots/jquery.inputmask/pull/879#issuecomment-123755855
> .
> 
> ## 

## 

Simen Bekkhus

**Comment by RobinHerbots** [comment]
@SimenB , 

pffff, ... those rules from the "standard" project just don't match with me ;-)

I went over to eslint and created a ruleset which exclude what I don't like.

**Comment by RobinHerbots** [comment]
@SimenB , 

There are still lots of eslint issues in the code but they will vanish in time.  Thx for the support and pushing  ;-)

Now I will have a look at karma.

**Comment by SimenB** [comment]
@RobinHerbots Ok, great! I'll rebase the karma one. Was a new release 2 days ago of `karma-qunit`, should be cleaner code now :smile:

**Pull request closed without merging**
