### PR TITLE
Optional Masks

### PR DESCRIPTION
**Pull request by rosshadden**
I implemented the ability to add optional masks.

The behavior works as follows:
Given an input element with a mask of `99999[-9999]` (zip code), if the field is empty the user will see `_____-____` when the field has focus, and '' when it does not.
When the user has typed `12345`, they will see `12345-____` when the field has focus, and `12345` when it does not.

In order to use this feature, make sure `clearIncomplete: true` is set in the options.  When the required part of the field is not completely filled out, it will erase the entire field.  When the required part is filled out but the optional part is not, it will only clear the optional.

For convenience in implementing this feature, I also added the placeholder to `data('inputmask')` of the element.  This is useful because the field's placeholder will either be the default or an overridden one, and AFAIK there was no easy way of accessing this otherwise.

Update:  The following is no longer true:

> This will only work if the placeholder is a 1-character string.  I can fix this, but I wanted to get the feature out into the world first.

Please let me know what you think.

### CODE REVIEW

**Comment by rawsp33d** [comment]
I have confirmed that this also works with the example mask '(999) 999-9999[ x9999]'.

**Comment by rawsp33d** [comment]
I'm fighting with getting a mask like:

``` javascript
$('#test').inputmask('99/99[/99]',{
    clearIncomplete:true,
    placeholder:    'ab/cd/ef'
});
```

to work, because I need to make sure that `value[i] !== data.placeholder[i % data.placeholder.length]` ([line 521](https://github.com/rosshadden/jquery.inputmask/blob/master/jquery.inputmask.js#L521)), but this means the '/' does not pass this test, screwing up the rest of the results.  Maybe we need a way for the mask to label all items that are in both the original mask (`99/99[/99]`) and the computed placeholder (`ab/cd/ef`) as symbols, in `data('inputmask').tests[i]`, where `i` is the position of the '/' in this case.

**Comment by RobinHerbots** [comment]
Hi Ross,

Why did you close the pull request?

With optional masks I had something else in mind then your implementation.  But I am willing to include the changes or the idea to clear the optional elements from the mask when losing focus.  In a previous issue someone else also asked about that kind of functionality.

What you did with the readme is amazing ;-)  I definitly have to have a look at markdown myself.

**Comment by rawsp33d** [comment]
If you want, I can make the readme it's own pull request, so you can just easily merge it in (or so I'm told).

**Pull request merged**
