### PR TITLE
Support for oncomplete event fire on blur

### PR DESCRIPTION
**Pull request by dasmfm**
Oncomplete fires on blur if required part of the mask is entered.
It's useful for me, maybe it'll also be useful for other plugin users.

### CODE REVIEW

**Comment by RobinHerbots** [comment]
But then the event should already be fired as you typed the last char to complete the mask.  So why do you need the extra event on blur?

**Comment by dasmfm** [comment]
For example, I have the following mask: 99[999]
I also have onincomplete event which makes input field red onblur, and oncomplete event which makes it white again.

So I input "9", blur -> field is red
And now to make it white I need to enter 4 more digits, while I need only one digit to complete the form.

There are a better way (to fire "oncomplete" right when required part of mask is entered), but I wasn't able to make it works :(

**Comment by RobinHerbots** [comment]
This issue is the same as issue 108.

I will fix that one soon.

**Comment by RobinHerbots** [comment]
Now I understand, ... the optional mask is complete because the iscomplete check happens after calling the clearoptionalTail, ...

We need to optimize the iscomplete fn to take optionality into account

**Comment by RobinHerbots** [comment]
hmm, when is the mask 99[99] complete?  when should it trigger?  1 => incomplete 12 => complete 123 => incomplete 1234 => complete, ....  sound this correct?  so when typing 1234 we have 2 times complete and 2 times incomplete!

What is considered as correct behavior?  does this belong in an inputmask?  or should this be handled separate?

**Comment by dasmfm** [comment]
I think it should fire "complete" when the non-optional part of mask is complete.
Which means, when mask is 99[99]:
1 => nothing fires (incomplete fires on blur)
12 => complete fires
123 => nothing fires
1234 => nothing fires

When I have mask 99[99] - I want from 2 to 4 digits, 3 is also correct.

**Comment by lucianogreiner** [comment]
I don't agree with that. I think for your case all of these can be considered as completed:

99
999
9999

so, if the value entered meets the mask requirements, then it should always call onComplete.

About onIncomplete, as the opposite, it should be called when there is any interaction with the field in which the result doesn't meet the mask. So, besides of '9' be incomplete, it should take into account that the user might be clearing the field, so this is a situation to fire the onIncomplete too.

**Comment by dasmfm** [comment]
But why should you need 3 onComplete events a row?
For my, 'oncomplete" means that the field is valid for a future work - no matter 2, 3 or 4 digits are there.

**Comment by lucianogreiner** [comment]
I have computations to perform on another fields based on the value of the user inputs in a field, so anything he performs there in which could be considered as valid would interest me.

**Comment by dasmfm** [comment]
Well, you're right. Then I see 2 ways:
1. Fire 'oncomplete' every time the field is valid.
2. Make some config param to know even we need to fire event every time or just once when it's complete.

Second one looks flexible and better to me, but I wouldn't be so sad if my 'oncomplete" will work several times :)

**Comment by RobinHerbots** [comment]
I depends how you interprete the optional part, ... when you see it as a whole meaning

99[99]

~   99  or 9999 then it should trigger as I mentioned before

if you see it as 

99 or 999 or 9999 then it should fire in the 3 cases

Luciano, there is already an oncleared event

**Comment by lucianogreiner** [comment]
Yeah, i am aware of the onCleared event, but it didn't work for me either.

I am trying to integrate inputmask with Angular, so i need basically to catch everything that happens on the field so i can update the underlying model. I can share the directive here if you guys think it's useful.

**Comment by RobinHerbots** [comment]
Please share ;-)

Is angular comparable to knockout?

For me the oncleared and onincomplete fire (incomplete fires on blur) like expected.  Only with optional mask there is the issue.

So some context code would help.

**Comment by sompylasar** [comment]
I agree with https://github.com/RobinHerbots/jquery.inputmask/pull/117#issuecomment-9485871
except one thing: "nothing fires" should be read as "fire the new 'input' event".

The "complete" and "incomplete" events are the signals that the field got into one of its final states. But it has got non-final states, too, and the transition between them is not signaled.

That would help with https://github.com/RobinHerbots/jquery.inputmask/pull/117#issuecomment-9489251

**Comment by RobinHerbots** [comment]
I agree, but I have to verify if there is impact when I fire the input
event myself.

2012/10/16 John Babak notifications@github.com

**Comment by lucianogreiner** [comment]
Well, in essence we might say so, because one of the principles of Angular is the two-way bindings like Knockout, but we don't need to actually declare the bindings with Angular, they all are automatic. And the biggest advantage is the ability to actually extend the HTML markup in order to create your own directives or to enhance the behavior of an existing one.

module.directive('mask', function() {
    return {
        restrict : 'A',
        require : '^ngModel',
        replace: true,
        link : function($scope, $element, $attr, $controller) {
                        var clear = function() {
                              $controller.$setViewValue('');
                        };
            $element.inputmask($attr.mask, {
                placeholder : $attr.placeholder,
                autoUnmask : true,
                clearIncomplete : false,
                oncomplete : function() {
                    $controller.$setViewValue($element.val());
                },
                onincomplete : clear,
                oncleared : clear,
                clearMaskOnLostFocus: true,
                numericInput : $attr.numeric === undefined ? false : true
            });
        }
    };
});

**Comment by RobinHerbots** [comment]
can you replace the 
onincomplete : clear,
oncleared : clear,

with onincomplete : function(){ alert('incomplete');},
oncleared : function(){ alert('cleared');},

just for a test, ...

**Comment by RobinHerbots** [comment]
Hi All, 

As you can see in the milestones I moved most issues to a later version.  I moved this issue to v2.0 because to solve this correctly I need to fully implement the optional masks.  I will implement the event as seeing the optional part as a whole.  See eventhandling as I described above.  But I will trigger the input event on every input. 

For the moment I added already the input trigger in dev so you can check when there is some input. (please report if you find issues in the dev version) The complete event isn't aware of optional masks at the moment neither does onincomplete.  Normally with the input trigger you can workaround this for the moment.

In milestone 1.2 are 2 minor issues left; fix these fast ;-)  After those I will start with the optional masks and this issue. 

Best regards, 

Robin

**Comment by RobinHerbots** [comment]
Strange, issues seems to close automagically??  Probably the github app on android

**Pull request closed without merging**
