### PR TITLE
In strict mode code, functions can only be declared at top level 

### PR DESCRIPTION
**Pull request by pogorivan**
or immediately within another function.

### CODE REVIEW

**Comment by RobinHerbots** [comment]
@pogorivan , 

Thx for the notify, I fixed up my eslint config and made the changes myself.

Best regards,
Robin

**Comment by pogorivan** [comment]
@RobinHerbots ,
I still have a problem related to this when building my app with gulp uglify.

> `Error: Error transforming bundle with 'uglify' plugin: In strict mode code, functions can only be declared at top level or immediately within another function.`

**Comment by RobinHerbots** [comment]
@pogorivan , 

I made the changes in the 5.x branch.  Merging the PR in 4.x

**Comment by pogorivan** [comment]
Thanks!

**Pull request merged**
