### PR TITLE
Move jQuery dependency to peerDependencies and add David-badges

### PR DESCRIPTION
**Pull request by SimenB**
As a plugin you should have your jQuery-dependency as a peerDependency.
jQuery should also be a devDependency, as it's used when running tests.

Source: http://blog.nodejs.org/2013/02/07/peer-dependencies/

In addition I added the nice dependency-badges from https://david-dm.org

### CODE REVIEW

**Comment by RobinHerbots** [comment]
@SimenB , 

Thx.

**Comment by RobinHerbots** [comment]
@SimenB , 

Just an quetion.  Is there an easy way to resolve a dependency with requirejs from the node-packages folder.

**Comment by SimenB** [comment]
Hmmm, I'm not sure. I suppose you should be able to just enter the relative path, but I haven't tested it.

I'll be able to test it this weekend if you haven't figured it out by then :smile:

**Comment by RobinHerbots** [comment]
@SimenB , 

If you set the path to node-modules/... it works, but is it is pity that he cannot autoresolve from the node-modules, ... in the package.json there is all info available but it is not auto-loaded by requirejs.

I would expect more integration of requirejs with bower & npm.  It would be great if requirejs searches in the bower-components & node-modules and readout the .json configs

**Pull request merged**
