### PR TITLE
Update jquery.inputmask.bundle.js

### PR DESCRIPTION
**Pull request by FRAGnatt**
Fix fatal if I tried to use 
jQuery('#nonameSelector').inputmask({'mask': 'MyMASK'})
jQuery('#nonameSelector').inputmask('hasMaskedValue')

### CODE REVIEW

**Comment by RobinHerbots** [comment]
@FRAGnatt , 

Can you make the changes in the files in the src folder.

Thx

**Comment by FRAGnatt** [comment]
Please retest my code. input.length > 0 works 100%
but this.length, I don't test

**Comment by RobinHerbots** [comment]
@FRAGnatt , 

I can agree but I cannot accept changes only on the bundle file as it is generated and will be overwritten.  You need to make the changes on the js/jquery.inputmask.js.

**Comment by FRAGnatt** [comment]
Oh sorry I commited new commit, but not pushed to your branch

**Pull request closed without merging**
