### PR TITLE
Use inline regexp when possible

### PR DESCRIPTION
**Pull request by vsn4ik**
https://jsperf.com/regexp-test-vs-match-m5

Fix access permission (https://github.com/RobinHerbots/jquery.inputmask/commit/6cb8dac65e94057585267476a9d331044cef8b7f#commitcomment-15381146).

### CODE REVIEW

**Comment by RobinHerbots** [comment]
@vsn4ik , 

Shouldn't it be iemobile = /iemobile/i.test(ua), instead of iemobile = /iemobile/i.text(ua),??

What do you mean with the Fix access permission comment?

**Comment by vsn4ik** [comment]
`js/inputmask.js` is not execution file (linux file permission: `x`, ex. chmod 7 (rwx).

**Comment by RobinHerbots** [comment]
@vsn4ik , 

Should a .js file be executable?  And do the permissions retain through git?

**Comment by vsn4ik** [comment]
@RobinHerbots I do not know how to set the git and whether he knows how to handle this. Yes, js file can be executable, ex: Less compiler (lessc). Thanks for merge.

**Pull request merged**
