### PR TITLE
Add support for .NET projects

### PR DESCRIPTION
**Pull request by williamthiago**
Robin,

I added support for nuget.org package manager to simplify installation .NET projects.

if you are interested, I can change the administration's owner package, or upgrade the package whenever you update the library.

Sorry for my english...

### CODE REVIEW

**Comment by williamthiago** [comment]
link to package

https://nuget.org/packages/jQuery.InputMask

**Comment by RobinHerbots** [comment]
Hi William,

Looks great ;-)

I see that the jQuery.InputMask.1.0.0.nupkghttps://github.com/williamthiago/jquery.inputmask/blob/master/nuget/jQuery.InputMask.1.0.0.nupkg
is
a binary.  Can you explain in short howto create a nuget package. (I know
what they are and the benifit, but never took the time to look into it
closer)

best regards,

Robin

2012/12/20 williamthiago notifications@github.com

**Comment by williamthiago** [comment]
Its really easy.
It was created by nuget.exe software, or by the GUI version (I use this), documented here

http://docs.nuget.org/docs/creating-packages/creating-and-publishing-a-package
http://docs.nuget.org/docs/creating-packages/using-a-gui-to-build-packages

On package contents, I added only a folder structure and yours js files:

\Scripts
  - jquery.inputmask.js
  - jquery.inputmask.extensions.js
...

package-explorer-lib-folder

**Comment by RobinHerbots** [comment]
Oeps, didn't need to be closed

**Pull request closed without merging**
